export const insectPrompts = [
  "A close-up macro of a dragonfly perched on a thin reed near a calm pond, its transparent wings shimmering in the sunlight.",
  "A detailed macro shot of a monarch butterfly feeding on a cluster of lavender flowers, with its wings spread wide.",
  "A macro image of an ant carrying a large crumb back to its nest, the ground around it littered with tiny pebbles and leaves.",
  "A close-up of a blue morpho butterfly resting on a large green leaf, its vibrant blue wings contrasting against the deep green background.",
  "A macro shot of a praying mantis hidden among green leaves, its large eyes and folded arms clearly visible.",
  "A close-up of a beetle climbing up a blade of grass, the texture of its shiny shell and tiny legs in sharp detail.",
  "A macro image of a bumblebee hovering over a sunflower, collecting pollen with its fuzzy body.",
  "A detailed shot of a caterpillar munching on a leaf, with tiny droplets of dew visible on the leaf's surface.",
  "A close-up macro of a grasshopper camouflaged among tall grasses, with its legs poised to jump.",
  "A macro image of a spider weaving its web between two branches, the fine strands of silk glistening in the sunlight.",
  "A close-up of a ladybug resting on a delicate flower petal, the contrast of red and black against the soft pastel colors.",
  "A detailed macro of a butterfly emerging from its chrysalis, wings still wet and crumpled.",
  "A close-up shot of a wasp building its nest, carefully placing a piece of chewed wood pulp in position.",
  "A macro image of a firefly glowing softly in the twilight, with the surrounding foliage dimly lit.",
  "A close-up of a moth resting on tree bark, its wings perfectly blending with the textured surface.",
  "A macro shot of a honeybee in mid-flight, approaching a flower in full bloom, with its wings blurred by motion.",
  "A detailed image of an aphid on the underside of a green leaf, surrounded by tiny water droplets.",
  "A close-up of a cicada clinging to the side of a tree trunk, with its exoskeleton gleaming in the sunlight.",
  "A macro shot of a dung beetle rolling a ball of dung across a sandy terrain, showcasing its strength and determination.",
  "A close-up of a butterfly drinking nectar from a coneflower, with its long proboscis clearly visible.",
  "A detailed macro of a spider’s web covered in morning dew, each droplet reflecting the surrounding landscape.",
  "A close-up of a green lacewing perched delicately on a stem, with its delicate wings spread out.",
  "A macro image of a leafcutter ant carrying a large piece of leaf through a dense forest floor.",
  "A close-up of a ladybug on a daisy, its red and black spots standing out against the white petals.",
  "A macro shot of a butterfly feeding on a thistle flower, with the intricate patterns on its wings in sharp focus.",
  "A detailed image of a dragonfly’s compound eyes, capturing the tiny facets in high detail.",
  "A close-up of a beetle crawling over a mossy log, with the sunlight filtering through the forest canopy above.",
  "A macro image of a caterpillar preparing to form a chrysalis, clinging to a twig.",
  "A close-up shot of an ant colony at work, with ants moving in and out of their underground nest.",
  "A macro image of a butterfly resting on a bright yellow flower, with its wings closed, showcasing the underside pattern.",
  "A detailed close-up of a honeybee inside a flower, covered in pollen.",
  "A macro shot of a grasshopper eating a blade of grass, with its powerful mandibles in focus.",
  "A close-up of a moth camouflaged on a tree trunk, blending perfectly with the bark.",
  "A macro image of a dragonfly resting on a reed, its iridescent body reflecting various colors in the light.",
  "A close-up of a spider hiding in a flower, waiting to ambush its prey.",
  "A detailed macro shot of a cicada’s wings, showing the delicate veins and transparent surface.",
  "A close-up of a beetle on a fallen log, with a background of green leaves and sunlight filtering through the trees.",
  "A macro image of a butterfly landing on a leaf, preparing to take flight.",
  "A close-up of a bumblebee gathering nectar from a clover flower, with the surrounding grass softly blurred.",
  "A detailed shot of a spider’s web in the early morning light, covered in dew drops.",
  "A close-up of a dragonfly perched on a rock by a stream, its wings spread wide to soak up the sun.",
  "A macro shot of a butterfly sipping nectar from a zinnia, with its colorful wings fully open.",
  "A close-up of an ant exploring the surface of a mushroom, with the forest floor blurred in the background.",
  "A macro image of a beetle climbing over a rough stone, the texture of its exoskeleton and the stone in sharp detail.",
  "A close-up of a moth on a leaf, its muted colors blending seamlessly with its surroundings.",
  "A macro shot of a praying mantis watching its prey, with its large, piercing eyes in focus.",
  "A close-up of a butterfly on a vibrant red flower, with its wings reflecting the sunlight.",
  "A detailed macro of a spider crawling on a mossy rock, with its eight legs spread out.",
  "A close-up of a honeybee collecting pollen from a field of wildflowers, with the surrounding blossoms softly blurred.",
  "A macro image of a caterpillar on a twig, with its colorful segments and tiny legs in focus.",
  "A close-up of a ladybug flying away from a leaf, its wings just beginning to unfold.",
  "A macro shot of a grasshopper camouflaged in the dry grass, almost invisible except for its eyes.",
  "A close-up of a beetle nestled in the petals of a flower, with the delicate petals in sharp detail.",
  "A detailed macro image of a spider's web stretching between two branches, with tiny insects trapped within.",
  "A close-up of a butterfly resting on a sunflower, with its wings catching the early morning light.",
  "A macro shot of an ant carrying a piece of food across a forest floor, surrounded by fallen leaves and twigs.",
  "A close-up of a bumblebee hovering near a lavender bloom, with the surrounding flowers softly blurred.",
  "A macro image of a dragonfly perched on a twig, with the texture of its wings and body in sharp focus.",
  "A close-up of a butterfly on a bright red flower, with its long proboscis reaching into the bloom.",
  "A macro shot of a beetle crawling over a log, with the bark and surrounding moss detailed and textured.",
  "A close-up of a spider suspended in its web, with the fine strands glistening in the sunlight.",
  "A detailed macro image of a honeybee resting on a flower, with pollen visible on its legs and body.",
  "A close-up of a butterfly drinking from a flower, its wings spread wide to show off its vibrant colors.",
  "A macro shot of a dragonfly hovering above a pond, its wings catching the light and creating reflections on the water below.",
  "A close-up of a beetle climbing up a tree trunk, with the rough bark and surrounding foliage in the background.",
  "A macro image of a spider weaving its web among tall grasses, the strands of silk catching the early morning dew.",
  "A close-up of a butterfly resting on a blade of grass, with the background softly blurred.",
  "A detailed macro shot of a honeybee on a sunflower, its body covered in golden pollen.",
  "A close-up of a dragonfly resting on a leaf near a calm pond, with the sunlight reflecting off its wings.",
  "A macro image of a butterfly feeding on a daisy, with its wings closed, showcasing the intricate patterns on the underside.",
  "A close-up of a beetle crawling on a rock, with the sunlight highlighting its shiny exoskeleton.",
  "A macro shot of a spider hiding in a flower, waiting for an unsuspecting insect to come close.",
  "A close-up of a grasshopper poised to jump from a blade of grass, with its strong legs in focus.",
  "A detailed macro image of a dragonfly perched on a reed, its transparent wings catching the light.",
  "A close-up of a butterfly resting on a colorful bloom, with its wings spread wide to soak up the sun.",
  "A macro image of a beetle on a mossy log, with the surrounding forest floor softly blurred.",
  "A close-up of a ladybug on a bright yellow flower, with its red and black spots standing out against the vibrant background.",
  "A detailed macro shot of a honeybee collecting nectar from a cluster of wildflowers, with the surrounding petals and leaves in soft focus.",
  "A close-up of a spider in its web, with tiny insects caught in the strands, and the web glistening with dew.",
  "A macro image of a butterfly on a thistle, with its delicate wings and the sharp spines of the flower in sharp focus.",
  "A close-up of a dragonfly perched on a leaf, with the surrounding water and reeds softly blurred in the background.",
  "A macro shot of a beetle climbing up a stem, with the sunlight catching the metallic sheen of its exoskeleton.",
  "A close-up of a grasshopper hiding in the grass, almost invisible except for its sharp eyes.",
  "A detailed macro image of a butterfly feeding on a flower, with its wings catching the sunlight.",
  "A close-up of a honeybee hovering over a sunflower, with the surrounding petals softly blurred.",
  "A macro shot of a dragonfly resting on a stone, with the texture of its wings and the stone in sharp focus.",
  "A close-up of a spider crawling over a leaf, with its legs spread out and the leaf’s texture in sharp detail.",
  "A macro image of a butterfly on a bright orange flower, with its wings fully open to soak up the sun.",
  "A close-up of a beetle on a branch, with the rough bark and surrounding foliage softly blurred.",
  "A detailed macro shot of a honeybee covered in pollen, resting on a vibrant flower.",
  "A close-up of a dragonfly perched on a twig, with the sunlight catching its iridescent wings.",
  "A macro image of a butterfly feeding on a clover flower, with the surrounding grass softly blurred.",
  "A close-up of a beetle crawling on a leaf, with the leaf’s veins and the beetle’s legs in sharp focus.",
  "A macro shot of a spider hiding in a flower, waiting to ambush its prey.",
  "A close-up of a butterfly resting on a bright yellow flower, with its wings catching the sunlight.",
  "A detailed macro image of a dragonfly’s eyes, capturing the tiny facets and reflections.",
  "A close-up of a grasshopper poised on a blade of grass, with the background softly blurred.",
  "A macro image of a honeybee collecting nectar from a daisy, with the surrounding petals and leaves softly blurred.",
  "A close-up of a beetle climbing up a tree trunk, with the rough bark and surrounding foliage softly blurred.",
  "A macro shot of a spider spinning its web, with the strands of silk glistening in the morning dew.",
];
